version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Running npm install
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - template.yaml
    - ./dist/index.js
  discard-paths: yes 
