version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Running npm install
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - mv ./dist/index.js ..
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - index.js
    - template.yaml
